dist: xenial
language: generic
addons:
  apt:
    packages:
    - python3-pip
    - python3-setuptools
    - arc
    - arj
    - bsdtar
    - cpio
    - lcab
    - rar
    - zip
    - zoo
install:
- python3 -m pip install --user pydiatra pyflakes
- python3 -m pip install --user pygments restructuredtext-lint
script:
- make -C 7zip
- make -C ar
- make -C arc
- make -C arj
- make -C cab
- make -C cpio
- make -C rar
- make -C tar
- make -C zip
- make -C zoo
- .private/update-readme
- git diff --exit-code
- grep -Po '(?<=<)https:\S+/download/\S+(?=>)' README
  | wget -O /dev/null -nv -i -
- python3 -m pydiatra .
- python3 -m pyflakes .
- restructuredtext-lint --encoding=UTF-8 README

# vim:ts=2 sts=2 sw=2 et
